### ISSUE TITLE
Download attachment unknown error SDK Release 3.2.1

### ISSUE THREAD

**Issue by shrinivasbayari** [forcedotcom/SalesforceMobileSDK-Windows#193]
I am trying to download an attachment using core REST api version 3.2.1

var restRequest = new RestRequest(Windows.Web.Http.HttpMethod.Get, AccountManager.GetAccount().InstanceUrl + "/services/data/v31.0/sobjects/Attachment/00P29000000HM0aEAG/Body");

 var client = SDKManager.GlobalClientManager.GetRestClient() ?? new RestClient(AccountManager.GetAccount().InstanceUrl);

var response = await client.SendAsync(restRequest); //Exception thrown here

Error: 

The text associated with this error code could not be found.
A connection with the server could not be established

Stack Trace: 

   at Salesforce.SDK.Rest.RestClient.<Send>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Salesforce.SDK.Rest.RestClient.<SendAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DJR.ViewModel.DJRMasterViewModel.<SendRequestAttachment>d__3c.MoveNext()

Any help highly appreciated.

**Comment by shrinivasbayari** [comment]
Fixed the issue by removing base URL (AccountManager.GetAccount().InstanceUrl) from the code.
The base URL is appended by the SDK itself.
